In [1]:
#import Library dealing with numbers
import pandas as pd

In [2]:
#reads containing in salary_data
dataset=pd.read_csv('salary_data.csv')

In [3]:
#shows the data in salary_data.csv
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [4]:
#shows the independent variable
independent=dataset[['YearsExperience']]

In [5]:
#shows the data in independent variable
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [6]:
#shows the dependent variable,next line shows the data in dependent variable
dependent=dataset[['Salary']]
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [10]:
#shows the data for training and test is being imported from the given data

from sklearn.model_selection import train_test_split
#spliting the data for training and test for both variables
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [11]:
#LinearRegression being imported
from sklearn.linear_model import LinearRegression
#regressor is a variable for LinearRregression class
regressor=LinearRegression()
#.fit function is called which is inside regressor
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
#weight is being called
weight=regressor.coef_
weight

array([[9360.26128619]])

In [13]:
#bais is being called
bais=regressor.intercept_
bais

array([26777.3913412])

In [14]:
#y value is predicted for for x_test
y_pred=regressor.predict(x_test)

In [15]:
#evaluation metric r2 being imported
from sklearn.metrics import r2_score
#r_score being calculated using actual y value and predicted y value
r_score=r2_score(y_test,y_pred)

In [16]:
r_score

0.9740993407213511

In [17]:
#for saving the model
import pickle
filename='finalized_model_linear.sav'

In [18]:
pickle.dump(regressor,open(filename,'wb'))

In [21]:
#loading file
loaded_model=pickle.load(open('finalized_model_linear.sav','rb'))
#checking the model
result=loaded_model.predict([[13]])

In [22]:
result

array([[148460.78806172]])